### ISSUE TITLE
Parse confinement.dat file

### ISSUE THREAD

**Issue by jferard** [geoffroychaussonnet/script_to_monitor_Covid19#10]
Should be easy to add the info to `dataParam` and use it later. The result could be a dict `country -> type -> [date]`. `plotCorelation.py` woud use `dataParam['Confinement']['Total'][0]`.

**Comment by geoffroychaussonnet** [comment]
I added the file confinement.dat because I found that the information is very interesting, so the file is now just a "storage" of raw data, with potential to be used later.
The way to parse the file or even to store the information in the file is still open. So if you want to rearrange the .dat file and/or write the parser, feel free ! :-)

**Comment by jferard** [comment]
>  I found that the information is very interesting

Indeed.

I'm writing the parser right now.

**Comment by jferard** [comment]
See https://github.com/geoffroychaussonnet/script_to_monitor_Covid19/pull/11
